language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm run build:docs
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: SnowTransfer
  on:
    branch: dev
env:
  global:
    secure: wS3epjoU7g8RRBmjYAFdRIaqPrhZGeb5LpJbAmVZlwAdWDHsLVVz/HRvJ/GEn7h9kd4F1YUPkEVBEAvB4egmYeBnW4biRWx4OnhDZ+8Pz0398PUegyR0WWSDazcugI2/LfOL+1lcMy//LMzOEgjCPh5ZzyZtORCtwY++y+zGxXt7Fz6OoUdmIK0Aae9RuZrCkaM81Y+H9mW4VqRXvaJ0CXhx/xQFhwN3qVjtN8KOFQLMwhLHtAChDUPyKwcSFlF2EBxt9l3RyOuQlkdSRBiUxJhDNUjjBRaYOT6tPj2jt3+gDmcE88TzzzbjckfrAjXK7TORMry6EzcqQ74hmADyAqcekfb0foU5WD1OVeIjEZBxA03fv+W5+zlIHcWMh63ePayEr2z5YUjMLiXzISYgSuvwijToJQXLHVWvEQivgz0n6ul0OTH2JEBKYHvRmqTqIAyFEH4Cvft7vofvN8z0a56XWorg/k3Hu90qfgMJTeLPBgu3+B9GNuXZGR70xpGfb5uzsfi0fc//DA9Frxj9ao0UqIh9PxKJxG6Tk0aHyFrxwlqLGzX2sVG6pT/eQH4jpOfBPTbq/AkBj2m5HPDvOOrSoS+chhHNp6uCht/G5N/AjPxk5gCpHHK0Tyu6MZ8lD+BJC2UjElA2v3tKkLoe+oMG/5G6INCmX5P/Ux8BZgw=
