language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm run build:docs
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: SnowTransfer
  on:
    branch: dev
env:
  global:
    secure: enPDA+d81UwWvK3my9MCDTTQizP9FuDQTh4YN29rg7ApEY7NIXipADf4JIyzZG4g2ej0lSPujkdm/OeSWGwkGIwkZ+cRqsqi/TbBdTl37s4Grf+oZKtBUx4uRiAQMGuINkaMzOD/9z5l4TzBje9JIeUdUCZVRaVY5wgOs0yNbm6QOBbnjoGQ9DQ32WZoj4ukwdGvcWCR8pp5Epb4PhVqmpTuhQ4vMrBxOJczvZO18bh+9gICTaRESs44iQOVp5sVsdFfdjHjtTZuS3pvLGoBDUxv7HzVsmc4AD/2ZkgJrqrgaihMT6A7Ae/ucz4Yj+hhyjuKceZZHUfxc9A8SnlZzmZdsqkGqabHpGU/xxEGwu5HRSvEMzmPreYwir0oB+pMPF2190595BNKRqfHErDyv6/xAGolFO6hJN4SU3XohOIgiQVUySq4wU08up/RW9LsYu3o0etz7lH89/3c5D8/v2bHkkEVz/Vk46+SDBmIGqr8K2HnIbaLccd1h8zaQ6fdMnLtitM/QjrWbnkOqTncwn6l0aCkRRy8e1NeN2oHHWuQzRVnrevqf/on98ZAbVTYEd28Yb+LXVNRhOA9LZCtdKXteg0TY9NkL74PW5ptzahxo280C/3ZiRGc71E7GI10D/MW0HlKNOEntVVo+coo1j83nlGdPJjScByrfDrVmhk=
